<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Php lut</name>
   <tag></tag>
   <elementGuidId>a2cfd071-5443-4ce0-9132-695467a7c716</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rso']/div/div/div/table/tbody/tr/td[2]/div/h3/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.cIkxbf > div.usJj9c > h3.r > a.l</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>l</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=&amp;ved=2ahUKEwjwhv7FjoXxAhWhKqYKHVWOB6AQjBAwA3oECBgQAQ&amp;url=https%3A%2F%2Ftuoitre.vn%2Fphap-luat.htm&amp;usg=AOvVaw3fK8zjIrnkV48Fv0vEd_oX</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ved</name>
      <type>Main</type>
      <value>2ahUKEwjwhv7FjoXxAhWhKqYKHVWOB6AQjBAwA3oECBgQAQ</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>return rwt(this,'','','','','AOvVaw3fK8zjIrnkV48Fv0vEd_oX','','2ahUKEwjwhv7FjoXxAhWhKqYKHVWOB6AQjBAwA3oECBgQAQ','','',event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctbtn</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cthref</name>
      <type>Main</type>
      <value>/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=&amp;ved=2ahUKEwjwhv7FjoXxAhWhKqYKHVWOB6AQjBAwA3oECBgQAQ&amp;url=https%3A%2F%2Ftuoitre.vn%2Fphap-luat.htm&amp;usg=AOvVaw3fK8zjIrnkV48Fv0vEd_oX</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pháp luật</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rso&quot;)/div[@class=&quot;hlcw0c&quot;]/div[@class=&quot;g&quot;]/div[@class=&quot;BYM4Nd&quot;]/table[@class=&quot;jmjoTe&quot;]/tbody[1]/tr[@class=&quot;mslg dmenKe&quot;]/td[@class=&quot;cIkxbf&quot;]/div[@class=&quot;usJj9c&quot;]/h3[@class=&quot;r&quot;]/a[@class=&quot;l&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rso']/div/div/div/table/tbody/tr/td[2]/div/h3/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pháp luật')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cập nhật tin tức, video clip thời sự, chính trị, xã hôi, phóng sự, ký ...'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thời sự'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='... tin tức, video clip nhanh nhất về các vụ án, hình sự, ký sự. Tư ...'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thế giới'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pháp luật']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=&amp;ved=2ahUKEwjwhv7FjoXxAhWhKqYKHVWOB6AQjBAwA3oECBgQAQ&amp;url=https%3A%2F%2Ftuoitre.vn%2Fphap-luat.htm&amp;usg=AOvVaw3fK8zjIrnkV48Fv0vEd_oX')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/h3/a</value>
   </webElementXpaths>
</WebElementEntity>
